resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  - name: configure-director
  plan:
  - task: configure-director
    file: pcf-pipelines/install-pcf/aws/tasks/config-director/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USER: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      AWS_KEY_NAME: {{aws_key_name}}
      PEM: {{PEM}}
      AWS_REGION: {{aws_region}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      db_host: {{db_host}}
      db_username: {{db_username}}
      rds_password: {{rds_password}}
      db_database: {{db_database}}
      s3_pcf_bosh: {{s3_pcf_bosh}}
      TRUSTED_CERTIFICATES: {{director_certificates}}
      management_services_subnet_reserved_ranges_z1: {{management_services_subnet_reserved_ranges_z1}}
      management_services_subnet_reserved_ranges_z2: {{management_services_subnet_reserved_ranges_z2}}
      management_services_subnet_reserved_ranges_z3: {{management_services_subnet_reserved_ranges_z3}}
      pas_subnet_reserved_ranges_z1: {{pas_subnet_reserved_ranges_z1}}
      pas_subnet_reserved_ranges_z2: {{pas_subnet_reserved_ranges_z2}}
      pas_subnet_reserved_ranges_z3: {{pas_subnet_reserved_ranges_z3}}
      services_subnet_reserved_ranges_z1: {{service_subnet_reserved_ranges_z1}}
      services_subnet_reserved_ranges_z2: {{services_subnet_reserved_ranges_z2}}
      services_subnet_reserved_ranges_z3: {{services_subnet_reserved_ranges_z3}}
