resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-install
  type: git
  source:
    branch: master
    uri: git@github.com:mujahidsof/pcf_install.git
    private_key: {{GIT_PEM}}
jobs:
- name: configure-director
  plan:
  - get: pcf-install
  - task: configure-director
    file: pcf-install/task/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USER: {{opsman_admin_username}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      aws_access_key_id: {{aws_access_key_id}}
      aws_secret_access_key: {{aws_secret_access_key}}
      AWS_KEY_NAME: {{AWS_KEY_NAME}}
      pcf_security_group: {{pcf_security_group}}
      key_pair: {{PEM}}}}
      PEM: {{PEM}}
      AWS_REGION: {{aws_region}}
      S3_ENDPOINT: {{S3_ENDPOINT}}
      db_host: {{db_host}}
      db_username: {{db_username}}
      rds_password: {{rds_password}}
      db_database: {{db_database}}
      s3_pcf_bosh: {{s3_pcf_bosh}}
      pcf_security_group: {{pcf_security_group}}
      TRUSTED_CERTIFICATES: {{director_certificates}}
      management_subnet_reserved_ranges_z1: {{management_subnet_reserved_ranges_z1}}
      management_subnet_reserved_ranges_z2: {{management_subnet_reserved_ranges_z2}}
      management_services_subnet_reserved_ranges_z3: {{management_subnet_reserved_ranges_z3}}
      pas_subnet_reserved_ranges_z1: {{pas_subnet_reserved_ranges_z1}}
      pas_subnet_reserved_ranges_z2: {{pas_subnet_reserved_ranges_z2}}
      pas_subnet_reserved_ranges_z3: {{pas_subnet_reserved_ranges_z3}}
      services_subnet_reserved_ranges_z1: {{services_subnet_reserved_ranges_z1}}
      services_subnet_reserved_ranges_z2: {{services_subnet_reserved_ranges_z2}}
      services_subnet_reserved_ranges_z3: {{services_subnet_reserved_ranges_z3}}
      services_subnet_id_z1: {{services_subnet_id_z1}}
      services_subnet_id_z2: {{services_subnet_id_z2}}
      services_subnet_id_z3: {{services_subnet_id_z1}}
      services_subnet_cidr_z1: {{services_subnet_cidr_z1}}
      services_subnet_cidr_z3: {{services_subnet_cidr_z2}}
      services_subnet_cidr_z3: {{services_subnet_cidr_z3}}
      services_subnet_gw_z1: {{services_subnet_gw_z1}}
      services_subnet_gw_z2: {{services_subnet_gw_z2}}
      services_subnet_gw_z3: {{services_subnet_gw_z3}}
      management_subnet_id_z1: {{management_subnet_id_z1}}
      management_subnet_id_z2: {{management_subnet_id_z2}}
      management_subnet_id_z3: {{management_subnet_id_z3}}
      management_subnet_cidr_z1: {{management_subnet_cidr_z1}}
      management_subnet_cidr_z1: {{management_subnet_cidr_z3}}
      management_subnet_cidr_z3: {{management_subnet_cidr_z3}}
      management_subnet_gw_z1: {{management_subnet_gw_z1}}
      management_subnet_gw_z2: {{management_subnet_gw_z2}}
      management_subnet_gw_z3: {{management_subnet_gw_z3}}
      pas_subnet_id_z1: {{pas_subnet_id_z1}}
      pas_subnet_id_z2: {{pas_subnet_id_z2}}
      pas_subnet_id_z3: {{pas_subnet_id_z3}}
      pas_subnet_cidr_z1: {{pas_subnet_cidr_z1}}
      pas_subnet_cidr_z2: {{pas_subnet_cidr_z2}}
      pas_subnet_cidr_z3: {{pas_subnet_cidr_z3}}
      pas_subnet_gw_z1: {{pas_subnet_gw_z1}}
      pas_subnet_gw_z2: {{pas_subnet_gw_z2}}
      pas_subnet_gw_z3: {{pas_subnet_gw_z3}}
      dns: {{dns}}
